# update xresources db so that urxvt uses Xresources info 
xrdb -merge .Xresources
# starts urxvt daemon
urxvtd -q -f -o
# set keyboard delay rate
kbdrate
# set the cursor
xsetroot -cursor_name left_ptr
# set dvp layout
#setxkbmap -rules xorg -model pc104 -layout us -variant dvp -option "ctrl:swapcaps" 
# make clipboard consistent across system
autocutsel -fork &
autocutsel -selection PRIMARY -fork &
# this binds the extra function keys
xbindkeys
# enables numlock automatically 
numlockx &
# dual monitor setup
#xrandr --output HDMI-A-0 --auto --rate 59.94 --output DVI-D-0 --auto --right-of HDMI-A-0
xrandr --output DVI-D-0 --auto --output HDMI-A-0 --auto --rate 59.94 --left-of DVI-D-0

# start ssh-agent if it is not already running
if [[ -z "$(pgrep -u aidan ssh-agent)" ]]; then
	eval $(/usr/bin/ssh-agent)
else
	echo "no doot"
fi

# needed to work properly
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

exec xmonad
