#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

#-----------------
# Aliases
#----------------

# Directory listing/navigation
alias l='ls --color=auto'  # colors output 
alias la='ls --color=auto -liha | less'  # colors output and gives extra deetz
alias lat='ls --color=auto -lihat | less'  # colors output, gives extra deetz and sorts by modification date
alias PS1='[\u@\h \W]\$ '
alias ..='cd ..'
alias rmd='rm -r'
alias cpd='cp -r'
#alias pwd='echo "current:" && pwd && echo "actual:" && pwd -P'
alias duh='sudo du -ha --max-depth 1 | sort -h'
alias duhl='du -ha --max-depth 1 | sort -h | less'
alias lsblk='lsblk -o NAME,MAJ:MIN,RM,SIZE,RO,TYPE,FSTYPE,MOUNTPOINT,UUID'
alias xel='grep EE /home/aidan/.local/share/xorg/Xorg.0.log'
alias xl='less /home/aidan/.local/share/xorg/Xorg.0.log'
alias cdir='ls -1 | wc -l'
alias adiff='diff --side-by-side --left-column'
alias fless='less +F'
alias lw='setsid libreoffice --writer;exit'
alias lc='setsid libreoffice --calc;exit'
alias cdd='cd /home/aidan/.config'
function mkcd
{
  command mkdir -p $1 && cd $1
}
function xd
{
	command cd /home/aidan/abs/xmage && wget $1 && sha256sum "$(basename $1)"
}

# pacman shorthands
function aget 
{ 
  command cd /home/aidan/abs/ && command git clone https://aur.archlinux.org/"$1".git && command cd "$1" && command vim PKGBUILD
}

alias get='sudo pacman -Syu --needed'
alias up='sudo pacman -Syu; rustup update; yay -Syua; sudo paccache -r -k 3; setsid xmonad --recompile ;pacman -Qqe > /home/aidan/.config/$(hostname)-current-packages.txt; sudo cp /home/aidan/.config/keyboard/us-dell /usr/share/X11/xkb/symbols/us; sleep 5; echo '
alias remove='sudo pacman -R'
alias aids='echo aidan'
alias install='sudo pacman -U'
alias smakepkg='makepkg -sif --config /home/aidan/.config/makepkg/makepkg.conf-chromebook'

#keyboard switching
alias sus='setxkbmap -layout us'
alias sud='setxkbmap -layout us -variant dvp'

# editing shortcuts
alias .bash='vim /home/aidan/.bashrc'
alias xmo='vim /home/aidan/.xmonad/xmonad.hs'
 
# shutdown/reboot/etc.
alias shut='systemctl poweroff'
alias reboot='systemctl reboot'

# setsid commonly used programs
alias lutris='setsid lutris; exit'
alias zoom='xset -dpms; xset s off; setsid zoom;exit'
alias gimp='setsid gimp'
alias thunderbird='setsid thunderbird'
alias ch='setsid chromium; exit'
alias chi='setsid chromium -incognito; exit'
alias calc='setsid gnome-calculator; exit'
alias vlc='setsid vlc'
alias geany='setsid geany'
alias fbreader='setsid FBReader'
alias term='setsid urxvt'
alias terme='setsid urxvt;exit'
alias gedit='setsid gedit'
alias lk='setsid luakit; exit'
alias audacity='setsid audacity; exit'
alias xournal='setsid xournal'
alias mtpaint='setsid mtpaint'
alias asteam='LANG=en_US.UTF-8 DRI_PRIME=1 steam'
alias ksteam='sudo pkill steam'
alias qt='setsid qutebrowser'
alias g='DRI_PRIME=1'
alias openttd='setsid openttd'
alias calibre='setsid calibre'
alias virtualbox='setsid virtualbox'
alias es='setsid evince'
function ev
{ command setsid evince "$1"; exit
}


# systemd 
alias status='sudo systemctl status --lines 80 --full' 
alias start='sudo systemctl start'
alias stop='sudo systemctl stop'
alias enable='sudo systemctl enable'
alias disable='sudo systemctl disable'
#alias sus='sudo systemctl suspend'

# other stuff
alias cmus='cd /home/aidan/media/music; cmus'
# old alias
#alias fl='wine "/home/aidan/.wine/drive_c/Program Files (x86)/FL Studio 12/FL.exe"'
# new alias
alias fl='wine "/home/aidan/.wine/drive_c/Program Files (x86)/Image-Line/FL Studio 12/FL.exe"'
alias syn='wine "/home/aidan/.wine/drive_c/Program Files (x86)/Syntorial/Syntorial.exe"'
alias time='timedatectl'
alias nu='setsid nuvolaplayer; setsid urxvt; exit'
alias roox='sudo bash /home/aidan/internet/wireless/roo.sh && startx && pulseaudio --start'
# alias roo='sudo bash /home/aidan/internet/wireless/roo.sh'
alias roo='sudo netctl start wlp9s0-RooCorner'
alias tk='sudo netctl start wlp9s0-Teksavvy'
alias eth='sudo bash /home/aidan/internet/ethernet.sh'
alias ethx='sudo bash /home/aidan/internet/ethernet.sh; startx'
alias edux='sudo bash /home/aidan/internet/wireless/edu.sh; startx'
alias uwx='sudo bash /home/aidan/internet/wireless/uw-un.sh; startx'
alias scan='sudo iwlist wlp1s0 scanning | less'
alias transmission='sudo systemctl start transmission; transmission-cli'
alias ext='sudo mount -U 9e9dc360-f406-43c6-bf5b-dcdd146a6372 /mnt/external && echo "/mnt/external was successfully mounted"'
alias uext='sudo umount /mnt/external'
alias ubuntu='sudo mount /dev/sda6 /mnt/ubuntu'
alias startx='cd; startx'
alias pig='ping -c 1 www.google.com'
alias pigs='ping www.google.com'
alias rpigs='ping 216.52.241.254'
alias deluge='setsid deluge'
alias xmind='setsid XMind'
#alias irssi='start xinetd; sleep 10;  irssi'
alias wup='sudo ip link set wlp9s0 up'
alias wd='sudo ip link set wlp9s0 down'
alias mtag='id3v2'
alias pc='curl -F c=@- http://ix.io'
alias p='bash /home/aidan/.config/scripts/pdf-dl.sh'
alias mc='wmname LG3D; setsid mage-client'
alias mcb='wmname LG3D; setsid mage-client-beta'
alias xmage='wmname LG3D; setsid mage-client'
alias wifi='sudo pkill dhcpcd && sudo pkill wpa_supplicant; sudo wifi-menu'
#alias rtp='setsid urxvt -e ssh -i /home/aidan/.ssh/id_rsa_alarm aidan@192.168.2.160 -t "stty stop undef; stty start undef ; screen -r rtorrent-torrentday" & ; setsid urxvt -e ssh -i /home/aidan/.ssh/id_rsa_alarm aidan@192.168.2.160 -t "stty stop undef ; stty start undef ; screen -r rtorrent"; exit'
alias rtp='setsid urxvt -e ssh -i /home/aidan/.ssh/id_rsa_alarm aidan@192.168.2.160 -t "stty stop undef; stty start undef ; screen -r rtorrent-torrentday" ; setsid urxvt -e ssh -i /home/aidan/.ssh/id_rsa_alarm aidan@192.168.2.160 -t "stty stop undef ; stty start undef ; screen -r rtorrent"; exit'
alias scpm='bash /home/aidan/.config/scripts/scp-alarm-dl-torrent-music.sh'
alias yt='youtube-dl --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s"'
alias yv='cd /tmp/; youtube-dl -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4'
alias sl='screen -r leela'
alias xs='xset -dpms; xset s off;exit'
alias th='ev cross-stitch/thorin-map-13-09-2020/ThorinsMap.pdf'

#####
# Git
####
# git auto-complete 
source /usr/share/git/completion/git-completion.bash
alias git='e git'
alias push='e git push -u origin master'
alias ga='git add .'
alias gp='git push origin master'
# set vim as default editor
export EDITOR="vim"


# privacy stuff
alias tchro='sudo systemctl start tor; setsid chromium --incognito --proxy-server="socks://localhost:9050"'
alias tlk='sudo systemctl start tor; sleep 5; setsid torify luakit'

# X stuff
alias merge='xrdb -merge ~/.Xresources'
#alias dual='bash /home/aidan/linux/arch/graphics/dual.sh'
#alias single='bash /home/aidan/linux/arch/graphics/single.sh'
alias dual='xrandr --output LVDS1 --auto --output VGA1 --auto --right-of LVDS1'
alias single='xrandr --output VGA1 --off'
alias sx='tk;startx'
# export BROWSER='/usr/bin/qutebrowser'

# Sound/music/language/game
alias pu='pulseaudio --start' 
alias pa='setsid pavucontrol'
#alias cmus='cd /home/aidan/music; cmus'
alias al='alsamixer'
alias m='setsid urxvt -e alsamixer;cd ~/; cmus'
alias e='LANG="en_CA.UTF-8"'
alias fe='cd /home/aidan/.config/gvbam/; e gvbam fe6.gba'
alias muse='setsid muse3'

# flash
alias org='ln -s /home/aidan/flash/flixel/org'

# ssh
alias sj='ssh aidan@192.168.2.39'
alias sx='ssh aidan@192.168.2.34'
alias st='ssh -i .ssh/id_rsa_alarm aidan@192.168.2.160'
alias sm='ssh maisy@192.168.2.162'


#---------------------------
# Flash stuff
#---------------------------

# get flex-sdk binaries in path

export PATH=/home/aidan/aur/flex-sdk/src/bin:$PATH

# add vim to path




# hacks 4 now
alias hack='sudo systemctl stop dhcpcd.service; sudo ip link set wlp9s0 down; sudo netctl start wlp9s0-RooCorner; startx'

alias chrono='cd /home/aidan/media/games/snes/chrono-trigger/; ./snes9x-gtk "Chrono Trigger.smc"'



#---------------------
# Other
#--------------------

#gets rid of Ctrl-q and Ctrl-s mappings that interfere with rtorrent
stty stop undef
stty start undef

#---------------------
# Games
#---------------------

alias metroid='cd /home/aidan/media/games/snes/super-metroid; setsid higan "Super Metroid (Japan, USA) (En,Ja).sfc"'
alias terraria='echo "copying world/player files"; cp -r /home/aidan/.local/share/Terraria/Players /home/aidan/.local/share/Terraria/Worlds /home/aidan/.config/Terraria/ && bash /home/aidan/"GOG Games"/Terraria/start.sh; cp -r /home/aidan/.local/share/Terraria/Players /home/aidan/.local/share/Terraria/Worlds /home/aidan/.config/Terraria/'
alias terraria-old='cd /home/aidan/media/games/pc/Terraria-1.3.5.3; bash ./start.sh'
alias ftl='bash "/home/aidan/GOG Games/FTL Advanced Edition/start.sh"'
alias breach='bash "/home/aidan/GOG Games/Into the Breach/start.sh"' 
alias celeste='xset -dpms; xset s off; cd "/home/aidan/media/games/pc/Celeste.v1.3.1.2/"; wine Celeste.exe'
alias hollow='xset -dpms; xset s off; cd "/home/aidan/media/games/pc/GOG Games/Hollow Knight/" ; bash start.sh'
alias spelunky='xset -dpms; xset s off; cd "/home/aidan/.wine/drive_c/GOG Games/Spelunky/"; wine Spelunky.exe;xrandr --output DVI-D-0 --auto --output HDMI-A-0 --auto --rate 59.94 --left-of DVI-D-0'
alias dsteam='xset -dpms; xset s off; setsid steam; exit'
alias undertale='xset -dpms; xset s off; cd "/home/aidan/.wine/drive_c/GOG Games/Undertale/"; wine UNDERTALE.exe'


alias keys="xev | grep -A2 --line-buffered '^KeyRelease' | sed -n '/keycode /s/^.*keycode \([0-9]*\).* (.*, \(.*\)).*$/\1 \2/p'"

# netctl debug
export NETCTL_DEBUG=yes

export MOZ_PLUGIN_PATH="/usr/lib/mozilla/plugins"

export PATH="$PATH:/root/.gem/ruby/2.6.0/gems/fpm-1.11.0/bin"
export PATH="$PATH:/root/.gem/ruby/2.6.0/bin"

# for electrical code reference
alias cce='ev ~/documents/work-stuff/electrician/CCE-2018.pdf'
alias cec='ev ~/documents/work-stuff/electrician/CEC-2018.pdf'
alias chq='ev ~/documents/work-stuff/electrician/Livre_Bleu_Hydro_Quebec10e_FEV2021.pdf'

# for xmonad binaries with stack
export PATH="$PATH:/home/aidan/.local/bin"
